# Collections implementation.
#
package(default_visibility = ["//visibility:public"])

java_library(
    name = "collect",
    srcs = glob(["*.java"]),
    deps = ["//main/java/com/github/ruinshe/collect/common"],
)
