# Test cases for collection implementation
#
package(default_visibility = ["//visibility:public"])

java_test(
    name = "collect",
    srcs = glob(["*.java"]),
    deps = [
        "//main/java/com/github/ruinshe/collect",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)
